version: '3.1'
services:
  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox-debug:3.141
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSIONS: 5
    restart: "always"
    ports:
      - "5900:5900"
    volumes:
      - ./testData:/selenium
    networks:
      main:
        aliases:
          - selenium-firefox
  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome-debug:3.141
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSIONS: 5
    restart: "always"
    ports:
      - "5901:5900"
    volumes:
      - ./testData:/selenium
    networks:
      main:
        aliases:
          - selenium-chrome
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:3.141
    ports:
      - "4444:4444"
    networks:
      main:
        aliases:
          - selenium-hub
networks:
  main:

